-- Truncate all tables to allow clean migration
TRUNCATE TABLE IF EXISTS users CASCADE;
TRUNCATE TABLE IF EXISTS pods CASCADE;
TRUNCATE TABLE IF EXISTS tutor_applications CASCADE;
TRUNCATE TABLE IF EXISTS tutor_assignments CASCADE;
TRUNCATE TABLE IF EXISTS students CASCADE;
TRUNCATE TABLE IF EXISTS sessions CASCADE;
TRUNCATE TABLE IF EXISTS reflections CASCADE;
TRUNCATE TABLE IF EXISTS academic_tracker CASCADE;
TRUNCATE TABLE IF EXISTS verification_docs CASCADE;
TRUNCATE TABLE IF EXISTS broadcasts CASCADE;
TRUNCATE TABLE IF EXISTS tutoring_sessions CASCADE;
